Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System.Security.Claims;
using Week5CaseStudy.Data;
using Week5CaseStudy.Models;

namespace Week5CaseStudy.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id, int page = 1, int pageSize = 2)
        {
            List<Category> categories = _context.Categories.ToList();
            ViewData["Categories"] = categories;

            Category category = _context.Categories.Find(id);

            PagedList<Post> model = new PagedList<Post>(_context.Posts
                .Include(p => p.User)
                .Include(p => p.Category)
                .Where(p => (p.Category_Id == category.Id && p.State == "Live"))
                .OrderByDescending(p => p.CreatedDate)  // İsteğe bağlı: Tarihe göre azalan sıralama
                    , page, pageSize);
            return View(model);
        }

    }
}

Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Week5CaseStudy.Data;
using Week5CaseStudy.Models;
using Week5CaseStudy.Services;
using PagedList.Core;
using System.Security.Claims;
namespace Week5CaseStudy.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IRepository _repository;
        public PostController(ApplicationDbContext context, IRepository repository)
        {
            _context = context;
            _repository = repository;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(int page = 1, int pageSize = 2)
        {
            List<Category> categories = _context.Categories.ToList();
            ViewData["Categories"] = categories;
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            PagedList<Post> model = new PagedList<Post>(_context.Posts
                .Include(p => p.User)
                .Include(p => p.Category)
                .Where(p => p.User_Id == userId)
                .OrderByDescending(p => p.CreatedDate)  // İsteğe bağlı: Tarihe göre azalan sıralama
                    , page, pageSize);

            return View(model);
        }

        public IActionResult PostDetails(int id)
        {
            List<Category> categories = _context.Categories.ToList();
            ViewData["Categories"] = categories;

            // Veritabanından ilgili post'u al
            Post post = _context.Posts.Find(id);

            if (post == null)
            {
                return NotFound(); // Post bulunamazsa 404 hatası döndür
            }

            return View(post);
        }
        public IActionResult Create()
        {
            List<Category> categories = _context.Categories.ToList();
            ViewData["Categories"] = categories;
            
            var model1List = _repository.GetModel1Data();
            var model2List = _repository.GetModel2Data();

            var myViewModel = new MyViewModel
            {
                PostList = model1List,
                CategoryList = model2List,
                // Diğer modellerin özellikleri
            };
          

            return View(myViewModel);
        }

        [HttpPost]
        public IActionResult Create(Post post)
        {
            List<Category> categories = _context.Categories.ToList();
            ViewData["Categories"] = categories;

            _context.Posts.Add(post);
            _context.SaveChanges();
            return Redirect("/Home");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free Website Template" name="keywords">
    <meta content="Free Website Template" name="description">

    <!-- Favicon -->
    <link asp-href-include="img/6509613.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link asp-href-include="css/style.css" rel="stylesheet">
</head>

<body>
    <div class="content">
        <!-- Navbar Start -->
        <div class="container p-0">
            <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
                <a href="" class="navbar-brand d-block d-lg-none">Navigation</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        @if (User.IsInRole(SD.Role_User))
                        {
                            <a class="nav-item nav-link active" asp-controller="Post" asp-action="List">My Blog</a>
                            <a class="nav-item nav-link active" asp-controller="Post" asp-action="Create">Create Post</a>

                        }

                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle active" data-toggle="dropdown">Categories</a>
                            <div class="dropdown-menu">
                                @if (ViewData["Categories"] != null)
                                {
                                    foreach (var category in ViewData["Categories"] as List<Category>)
                                    {
                                        <a asp-controller="Category" asp-action="Index" asp-route-id="@category.Id" class="dropdown-item">@category.Name</a>
                                    }
                                }
                            </div>

                        </div>

                    </div>

                </div>
                <partial name="_LoginPartial" />
            </nav>
        </div>
        <!-- Navbar End -->

        @RenderBody()

        <!-- Footer Start -->
        <div class="container py-4 bg-secondary text-center" style="margin-top:10px;">
            <p class="m-0 text-white">
                &copy; <a class="text-white font-weight-bold" href="#">www.codetogether.com</a>.  All Rights Reserved.
            </p>
        </div>
        <!-- Footer End -->

    </div>
  

    <!-- Back to Top -->
    <a href="#" class="back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>